### ISSUE TITLE
add `map` (like `bimap` for Either)

### ISSUE THREAD

**Issue by safareli** [natefaubion/purescript-variant#36]
`Either` has `bimap`, would be nice to have something like that for variant which takes record of functions, something like this:

``` purs
f :: forall r. Variant (foo :: String, baz :: Int | r) -> Variant (foo :: Array String, baz :: Number | r)
f = V.map
  { foo: \s -> [s,  "foo"]
  , baz: toNumber >>> _ + 9.0
  }
```

**Comment by natefaubion** [comment]
Do you mean that the user should provide an exhaustive handler for every case, or just for some subset?

**Comment by safareli** [comment]
probably subset would make more sense (because of variants are extensible)
